CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(128) UNIQUE,
    EMAIL VARCHAR(128) UNIQUE,
    PASSWORD VARCHAR(128),
    ABOUT_ME VARCHAR(128),
    SEX VARCHAR(128),
    AGE INTEGER,
    STATUS BOOLEAN
);
CREATE TABLE FRIENDSHIP (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SENDER_ID INTEGER REFERENCES USERS(ID),
    RECEIVER_ID INTEGER REFERENCES USERS(ID),
    STATUS VARCHAR(128)

);
CREATE TABLE TAGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(128),
    CREATOR_ID INTEGER REFERENCES USERS(ID)

);
CREATE TABLE USER_TAGS (
    USER_ID INTEGER REFERENCES USERS(ID),
    TAG_ID INTEGER REFERENCES TAGS(ID),
    PRIMARY KEY(USER_ID, TAG_ID)
);
CREATE TABLE MEETINGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SENDER_ID INTEGER REFERENCES USERS(ID),
    RECEIVER_ID INTEGER REFERENCES USERS(ID),
    LOCATION VARCHAR(128),
    STATUS VARCHAR(128)
);